# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-03 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_avgsites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avgsites',
            old_name='avg_a_value',
            new_name='a_value',
        ),
        migrations.RenameField(
            model_name='avgsites',
            old_name='avg_b_value',
            new_name='b_value',
        ),
        migrations.RenameField(
            model_name='sumsites',
            old_name='sum_b_value',
            new_name='a_value',
        ),
        migrations.RenameField(
            model_name='sumsites',
            old_name='sum_a_value',
            new_name='b_value',
        ),
    ]
