# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-09 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_auto_20170803_0628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvgSites',
        ),
        migrations.DeleteModel(
            name='SumSites',
        ),
    ]
