# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-06 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sites',
            old_name='site_id',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='a_value',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='b_value',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='site_name',
        ),
    ]
